//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomacaoAPIMantisBase2.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomacaoAPIMantisBase2.Queries.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `mantis_api_token_table` ;
        ///DELETE FROM `mantis_bug_history_table`;
        ///DELETE FROM `mantis_bug_text_table`;
        ///DELETE FROM `mantis_bug_table`;
        ///DELETE FROM `mantis_custom_field_table`;
        ///DELETE FROM `mantis_filters_table`  WHERE id &lt;&gt; 1;
        ///DELETE FROM `mantis_project_table`;
        ///DELETE FROM `mantis_tag_table`;
        ///DELETE FROM `mantis_user_table` WHERE username &lt;&gt; &apos;administrator&apos;;
        ///INSERT INTO `mantis_project_table` (`id`, `name`, `status`, `enabled`, `view_state`, `access_min`, `file_path`, `description`, ` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InicializaTestes {
            get {
                return ResourceManager.GetString("InicializaTestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `mantis_filters_table` (`id`, `user_id`, `project_id`, `is_public`, `name`, `filter_string`) VALUES (2, 1, 0, 0, &apos;filter1&apos;, &apos;v9#{&quot;_version&quot;:&quot;v9&quot;,&quot;_view_type&quot;:&quot;simple&quot;,&quot;category_id&quot;:[&quot;0&quot;],&quot;severity&quot;:[0],&quot;status&quot;:[0],&quot;highlight_changed&quot;:6,&quot;reporter_id&quot;:[0],&quot;handler_id&quot;:[0],&quot;project_id&quot;:[-3],&quot;resolution&quot;:[0],&quot;build&quot;:[&quot;0&quot;],&quot;version&quot;:[&quot;0&quot;],&quot;hide_status&quot;:[90],&quot;monitor_user_id&quot;:[0],&quot;sort&quot;:&quot;last_updated&quot;,&quot;dir&quot;:&quot;DESC&quot;,&quot;per_page&quot;:50,&quot;match_type&quot;:0,&quot;platform&quot;:[&quot;0&quot;],&quot;os&quot;:[&quot;0&quot;],&quot;os_build&quot;:[&quot;0&quot;],&quot;fixed_in_ver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsereFiltro {
            get {
                return ResourceManager.GetString("InsereFiltro", resourceCulture);
            }
        }
    }
}
